server:
  port: 8081
# dubbo配置
dubbo:
  application:
    name: dubbo-service-course
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry  # 所有服务配置连接监控中心，进行监控统计
  consumer:
    check: false # 服务启动健康不检查
# 数据库相关的配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.140:3306/gymnasium
    username: root
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 200MB  #设置单个文件的大小  因为springboot内置tomact的的文件传输默认为10MB
      max-request-size: 500MB   #设置单次请求的文件总大小
      enabled: true    #千万注意要设置该参数，否则不生效
# minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accesskey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
# mybatis-plus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 将相关的日志信息输出到控制台
  global-config:
    db-config:
      update-strategy: not_empty  # 在更新操作的时候，只更新非空和非NULL的字段
# 配置jwt
jwt:
  issuer: krisswen #颁发者
  secret: ${JWT_SECRET}  # 配置秘钥
  expiration: 30 # 配置过期时间

#不需要token验证的请求，逗号分隔配置
ignore:
  url: /api/login/login,/api/login/image

# 定义日志文件的输出格式
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'